### ISSUE TITLE
website issue

### ISSUE THREAD

**Issue by vpelss** [jquery/demos.jquerymobile.com#25]
as there is no way to report issues with your webpage... (When did email go out of fashion and why?)

one example:
https://demos.jquerymobile.com/1.4.5/datepicker/

Many of your examples fail as you point to http and https:
Mixed Content: The page at 'https://demos.jquerymobile.com/1.4.5/datepicker/' was loaded over HTTPS, but requested an insecure stylesheet 'http://cdn.rawgit.com/arschmitz/jquery-mobile-datepicker-wrapper/v0.1.1/jquery.mobile.datepicker.css'. This request has been blocked; the content must be served over HTTPS.

**Comment by mgol** [comment]
Thanks for the report.

Most jQuery sites have their own repositories under the jQuery org, that's the place to report issues with them.

As for this issue, I replaced a lot of HTTP links with HTTPS ones [in a series of commits](https://github.com/jquery/demos.jquerymobile.com/compare/v1.4.13...v1.4.14). There's a chance I may have made a mistake in one of the replacements; if that's the case, feel free to comment here & I'll have a look.

The datepicker page now seems to work fine so I'll close this.
